-- TSM V35.1: PostGIS subsurface and geotechnical stratification.
-- Horizontal CRS: EPSG:2966 (Indiana West). Vertical datum is stored separately.
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS subsurface_boreholes (
    borehole_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    operator TEXT NOT NULL DEFAULT 'PTDT-Sovereign-Twin',
    geom GEOMETRY(Point, 2966) NOT NULL,
    surface_elevation_m_navd88 NUMERIC(10, 3) NOT NULL,
    water_table_depth_m NUMERIC(8, 3),
    vertical_datum TEXT NOT NULL DEFAULT 'NAVD88',
    horizontal_crs TEXT NOT NULL DEFAULT 'EPSG:2966',
    logged_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    provenance_metadata JSONB NOT NULL,
    CONSTRAINT chk_borehole_crs
        CHECK (horizontal_crs = 'EPSG:2966'),
    CONSTRAINT chk_borehole_vertical_datum
        CHECK (vertical_datum = 'NAVD88'),
    CONSTRAINT chk_water_table_depth
        CHECK (
            water_table_depth_m IS NULL
            OR water_table_depth_m >= 0
        )
);

CREATE TABLE IF NOT EXISTS borehole_strata_layers (
    layer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borehole_id TEXT NOT NULL
        REFERENCES subsurface_boreholes(borehole_id)
        ON DELETE CASCADE,
    depth_top_m NUMERIC(8, 3) NOT NULL,
    depth_bottom_m NUMERIC(8, 3) NOT NULL,
    uscs_classification TEXT NOT NULL,
    cohesion_kpa NUMERIC(9, 3) NOT NULL,
    friction_angle_deg NUMERIC(6, 3) NOT NULL,
    bulk_density_kn_m3 NUMERIC(7, 3) NOT NULL,
    moisture_content_pct NUMERIC(7, 3),
    provenance_metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT chk_strata_depth
        CHECK (
            depth_top_m >= 0
            AND depth_bottom_m > depth_top_m
        ),
    CONSTRAINT chk_strata_strength
        CHECK (
            cohesion_kpa >= 0
            AND friction_angle_deg >= 0
            AND friction_angle_deg < 90
        ),
    CONSTRAINT chk_strata_density
        CHECK (bulk_density_kn_m3 > 0),
    CONSTRAINT chk_strata_moisture
        CHECK (
            moisture_content_pct IS NULL
            OR moisture_content_pct >= 0
        ),
    CONSTRAINT chk_uscs_nonempty
        CHECK (LENGTH(TRIM(uscs_classification)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_boreholes_spatial
    ON subsurface_boreholes USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_strata_borehole_id
    ON borehole_strata_layers (borehole_id);

CREATE OR REPLACE FUNCTION reject_overlapping_strata()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM borehole_strata_layers existing
        WHERE existing.borehole_id = NEW.borehole_id
            AND existing.layer_id <> COALESCE(NEW.layer_id, -1)
            AND NEW.depth_top_m < existing.depth_bottom_m
            AND NEW.depth_bottom_m > existing.depth_top_m
    ) THEN
        RAISE EXCEPTION
            'stratum depth interval overlaps an existing interval for borehole %',
            NEW.borehole_id;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_reject_overlapping_strata
    ON borehole_strata_layers;

CREATE TRIGGER trg_reject_overlapping_strata
BEFORE INSERT OR UPDATE ON borehole_strata_layers
FOR EACH ROW
EXECUTE FUNCTION reject_overlapping_strata();
