import { describe, expect, it } from 'vitest';
import { ACTIVE_RIVER_GAUGES, createUnavailableGauge } from '../frontend/river-gauges';
import { computeDatumProvenanceSha256, reconcileVerticalDatum } from '../../backend/datum-middleware';
import { createRiverCircuitBreaker, ingestRiverObservation } from '../../backend/river-network-api';
describe('V35.1 fail-closed contracts', () => {
  it('keeps unavailable gauge observations null', () => { const gauge = createUnavailableGauge(ACTIVE_RIVER_GAUGES[0]); expect(gauge.state).toBe('SOURCE_UNAVAILABLE'); expect(gauge.observedAt).toBeNull(); expect(gauge.stageFt).toBeNull(); });
  it('blocks NAVD88 conversion without an explicit transformation', () => { const observation = { value: 10, unit: 'ft' as const, datum: 'GAGE_DATUM' as const, observedAt: '2026-09-18T00:00:00Z', stationId: '03378500', provenance: { tokenId: 'source', authority: 'USGS', sourceUri: 'https://example.gov', transformationId: 'source', issuedAt: '2026-09-18T00:00:00Z', sha256: '0'.repeat(64) } }; expect(() => reconcileVerticalDatum(observation, null)).toThrow(); });
  it('cryptographically verifies datum provenance', () => { const base = { tokenId: 'tx-1', authority: 'USGS', sourceUri: 'https://example.gov/transform/1', transformationId: 'tx-1', issuedAt: '2026-09-18T00:00:00Z' }; const token = { ...base, sha256: computeDatumProvenanceSha256(base) }; const observation = { value: 10, unit: 'ft' as const, datum: 'GAGE_DATUM' as const, observedAt: '2026-09-18T00:00:00Z', stationId: '03378500', provenance: token }; const transformed = reconcileVerticalDatum(observation, { transformationId: 'tx-1', from: 'GAGE_DATUM', to: 'NAVD88', offset: 1.25, unit: 'ft', provenance: token }); expect(transformed.value).toBe(11.25); expect(transformed.datum).toBe('NAVD88'); expect(() => reconcileVerticalDatum(observation, { transformationId: 'tx-1', from: 'GAGE_DATUM', to: 'NAVD88', offset: 1.25, unit: 'ft', provenance: { ...token, authority: 'tampered' } })).toThrow('hash mismatch'); });
  it('fails closed when hydrologic source and cache are unavailable', async () => { const breaker = createRiverCircuitBreaker({ failureThreshold: 1 }); const result = await ingestRiverObservation('03378500', { fetch: async () => { throw new Error('offline'); } }, { read: async () => null, write: async () => undefined }, breaker); expect(result.status).toBe('SOURCE_UNAVAILABLE'); expect(result.observedAt).toBeNull(); expect(result.stageFt).toBeNull(); });
  it('serves stale last-known-good data after source failure', async () => { const breaker = createRiverCircuitBreaker({ failureThreshold: 1 }); const cached = { stationId: '03378500', observedAt: new Date(Date.now() - 1000).toISOString(), retrievedAt: new Date().toISOString(), stageFt: 12, dischargeCfs: 100, status: 'LIVE' as const, provisional: false, sourceUri: 'https://example.gov', cacheAgeSeconds: 0 }; const result = await ingestRiverObservation('03378500', { fetch: async () => { throw new Error('offline'); } }, { read: async () => cached, write: async () => undefined }, breaker); expect(result.status).toBe('STALE'); expect(result.stageFt).toBe(12); });
  it('opens circuit at threshold and rejects invalid thresholds', () => { const breaker = createRiverCircuitBreaker({ failureThreshold: 2 }); breaker.failure(1000); expect(breaker.allow(1001)).toBe(true); breaker.failure(1002); expect(breaker.allow(1003)).toBe(false); expect(() => createRiverCircuitBreaker({ failureThreshold: 0 })).toThrow(); });
});
