import{createServer,type IncomingMessage,type ServerResponse}from'node:http';import{randomUUID}from'node:crypto';import{CapabilityRegistry}from'../../../packages/registry/src/CapabilityRegistry.ts';import{CapabilityRouter}from'../../../packages/router/src/CapabilityRouter.ts';import{StaticPolicyEngine}from'../../../packages/policy/src/PolicyEngine.ts';import{UniversalCapabilityFabric}from'../../../packages/core/src/UniversalCapabilityFabric.ts';import{EchoProvider}from'../../../packages/provider-runtime/src/EchoProvider.ts';import{TsmEngineeringProvider}from'../../../packages/provider-runtime/src/TsmEngineeringProvider.ts';import{McpCapabilityProvider}from'../../../packages/mcp/src/McpCapabilityProvider.ts';import{OpenApiCapabilityProvider}from'../../../packages/openapi/src/OpenApiCapabilityProvider.ts';import{createJob,getJob}from'./jobs.ts';import type{CapabilityRequest,PermissionSet}from'../../../packages/contracts/src/index.ts';

const HOST=process.env.UACF_HOST??'127.0.0.1';const PORT=Number.parseInt(process.env.UACF_PORT??'8790',10);const MAX_BODY_BYTES=2*1024*1024;if(!Number.isInteger(PORT)||PORT<1||PORT>65535)throw new Error('UACF_PORT must be an integer between 1 and 65535');
const registry=new CapabilityRegistry();registry.register(new EchoProvider());registry.register(new TsmEngineeringProvider());
const mcpEndpoints=String(process.env.UACF_MCP_ENDPOINTS??'').split(',').map(x=>x.trim()).filter(Boolean);for(const endpoint of mcpEndpoints){try{const p=new McpCapabilityProvider({endpoint});await p.discover();registry.register(p)}catch(error){console.error('[UACF] MCP provider unavailable',{endpoint,error:String(error)})}}
const openapiSpec=process.env.UACF_OPENAPI_SPEC_JSON; if(openapiSpec){try{registry.register(new OpenApiCapabilityProvider(JSON.parse(openapiSpec),'env'))}catch(error){console.error('[UACF] OpenAPI spec rejected',{error:String(error)})}}
const policyRules=[{capability:'test.*',allow:true,permissions:[]},{capability:'tsm.engineering.*',allow:true,permissions:['tsm:engineering']},{capability:'tsm.hydraulic.*',allow:true,permissions:['tsm:hydraulic']},{capability:'tsm.autonomy.*',allow:true,permissions:['tsm:autonomy']},{capability:'tsm.hydrologic.*',allow:true,permissions:['tsm:hydrologic']},{capability:'tsm.geospatial.*',allow:true,permissions:['tsm:geospatial']},{capability:'*',allow:true,permissions:[]} ] as const;
const fabric=new UniversalCapabilityFabric(new CapabilityRouter(registry,new StaticPolicyEngine(policyRules)));
function sendJson(res:ServerResponse,status:number,payload:unknown):void{const body=JSON.stringify(payload);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'no-store','x-content-type-options':'nosniff'});res.end(body)}
function sendError(res:ServerResponse,status:number,code:string,message:string):void{sendJson(res,status,{success:false,error:{code,message}})}
async function readJson(req:IncomingMessage):Promise<unknown>{let size=0;const chunks:Buffer[]=[];for await(const chunk of req){const b=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);size+=b.length;if(size>MAX_BODY_BYTES)throw Object.assign(new Error('Request body exceeds 2 MiB limit'),{statusCode:413});chunks.push(b)}if(!size)return{};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw Object.assign(new Error('Request body must be valid JSON'),{statusCode:400})}}
function permissions(value:Record<string,unknown>):PermissionSet{const p=value.permissions;if(!p||typeof p!=='object')return{allow:[]};const allow=(p as Record<string,unknown>).allow;return Array.isArray(allow)&&allow.every(x=>typeof x==='string')?{allow}: {allow:[]}}
function buildRequest(value:Record<string,unknown>):CapabilityRequest{const ctx=value.context&&typeof value.context==='object'?value.context as Record<string,unknown>:{};return{capability:value.capability as CapabilityRequest['capability'],input:value.input,context:{requestId:typeof ctx.requestId==='string'&&ctx.requestId?ctx.requestId:randomUUID(),sessionId:typeof ctx.sessionId==='string'?ctx.sessionId:undefined,userId:typeof ctx.userId==='string'?ctx.userId:undefined,tenantId:typeof ctx.tenantId==='string'?ctx.tenantId:undefined,permissions:permissions(ctx)},options:value.options&&typeof value.options==='object'?value.options as CapabilityRequest['options']:undefined}}
function sse(res:ServerResponse):void{res.writeHead(200,{'content-type':'text/event-stream; charset=utf-8','cache-control':'no-cache, no-transform','connection':'keep-alive','x-content-type-options':'nosniff'});res.write(': connected\n\n')}
async function handle(req:IncomingMessage,res:ServerResponse):Promise<unknown>{const method=req.method??'GET';const url=new URL(req.url??'/',`http://${HOST}:${PORT}`);if(method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':process.env.UACF_CORS_ORIGIN??'http://localhost:3000','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'});return res.end()}res.setHeader('access-control-allow-origin',process.env.UACF_CORS_ORIGIN??'http://localhost:3000');
if(method==='GET'&&url.pathname==='/v1/health')return sendJson(res,200,{status:'ok',service:'uacf-gateway',version:'0.2.0',providers:registry.list().map(p=>p.id)});
if(method==='GET'&&url.pathname==='/v1/providers')return sendJson(res,200,{providers:await Promise.all(registry.list().map(async p=>({id:p.id,version:p.version,capabilities:p.capabilities.map(c=>c.id),health:await p.health()})))});
if(method==='GET'&&url.pathname==='/v1/capabilities'){const context={requestId:randomUUID(),permissions:{allow:[]}};return sendJson(res,200,{capabilities:await fabric.router.describeAvailableCapabilities(context)})}
if(method==='POST'&&(url.pathname==='/v1/execute'||url.pathname==='/v1/stream')){const payload=await readJson(req);if(!payload||typeof payload!=='object'||typeof(payload as Record<string,unknown>).capability!=='string')return sendError(res,400,'INVALID_INPUT','capability is required');const request=buildRequest(payload as Record<string,unknown>);const wantsJob=url.searchParams.get('async')==='true'||Boolean((request.options as Record<string,unknown>|undefined)?.async);if(wantsJob){const job=createJob(()=>fabric.execute(request));return sendJson(res,202,{jobId:job.id,status:job.status,poll:`/v1/jobs/${job.id}`,events:`/v1/jobs/${job.id}/events`})}if(url.pathname==='/v1/stream'){sse(res);const traceId=request.context.requestId;res.write(`event: execution.started\\ndata: ${JSON.stringify({traceId,capability:request.capability})}\\n\\n`);const result=await fabric.execute(request);res.write(`event: execution.completed\\ndata: ${JSON.stringify(result)}\\n\\n`);return res.end()}return sendJson(res,200,await fabric.execute(request))}
if(method==='GET'&&url.pathname.startsWith('/v1/jobs/')){const id=url.pathname.split('/')[3];const job=getJob(id);if(!job)return sendError(res,404,'NOT_FOUND','Job not found');if(url.pathname.endsWith('/events')){sse(res);for(const event of job.events)res.write(`event: job\\ndata: ${JSON.stringify(event)}\\n\\n`);if(job.status==='completed'||job.status==='failed'){res.write(`event: result\\ndata: ${JSON.stringify({status:job.status,result:job.result,error:job.error})}\\n\\n`);return res.end()}return res.end()}return sendJson(res,200,job)}
return sendError(res,404,'NOT_FOUND','UACF endpoint not found')}
const server=createServer((req,res)=>{void handle(req,res).catch((error:unknown)=>{const status=typeof error==='object'&&error!==null&&'statusCode'in error&&typeof error.statusCode==='number'?error.statusCode:500;if(!res.headersSent)sendError(res,status,status===500?'INTERNAL_ERROR':'INVALID_INPUT',error instanceof Error?error.message:'Internal server error');else res.destroy()})});server.listen(PORT,HOST,()=>process.stdout.write(`UACF gateway listening on http://${HOST}:${PORT}\n`));const shutdown=()=>{const timer=setTimeout(()=>process.exit(0),5000);timer.unref();server.close(()=>process.exit(0))};process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);