/** MapLibre layer catalog — Public Visualization Plane. Regulatory/effective layers are display-only. */
export type LayerAuthority = 'OBSERVATION' | 'REGULATORY' | 'PLANNING' | 'DERIVED' | 'VISUALIZATION' | 'CONTEXT';
export interface MapLayerSpec { id: string; title: string; authority_class: LayerAuthority; type: 'raster' | 'raster-dem' | 'vector-tile' | 'geojson' | 'arcgis-mapserver'; url: string; attribution?: string; notes?: string; defaultVisible?: boolean; maplibre?: Record<string, unknown>; }

export const MAP_LAYERS: MapLayerSpec[] = [
  { id: 'osm-base', title: 'OpenStreetMap', authority_class: 'CONTEXT', type: 'raster', url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png', attribution: '© OpenStreetMap', defaultVisible: false },
  { id: 'fema-nfhl', title: 'FEMA National Flood Hazard Layer', authority_class: 'REGULATORY', type: 'arcgis-mapserver', url: 'https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer', attribution: 'FEMA NFHL', notes: 'Effective FIRM/SFHA evidence for insurance. Layer 28 Flood Hazard Zones, 16 BFEs, 3 FIRM Panels, LOMA/LOMR and levee products are kept in the FEMA authority plane.', defaultVisible: false },
  { id: 'fema-firm-panels', title: 'FEMA FIRM Panels', authority_class: 'REGULATORY', type: 'arcgis-mapserver', url: 'https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer', attribution: 'FEMA NFHL / FIRM Panel data', notes: 'FEMA effective evidence; never merged with Indiana BAFM.', defaultVisible: false, maplibre: { arcgisLayerId: 3 } },
  { id: 'indiana-bafm', title: 'Indiana Best Available Flood Hazard Layer', authority_class: 'PLANNING', type: 'arcgis-mapserver', url: 'https://gisdata.in.gov/server/rest/services/Best_Available_Flood_Hazard_Layer/MapServer', attribution: 'Indiana DNR Division of Water', notes: 'Planning/construction and Indiana Flood Control Act context. Layers 104 and 438. NOT flood insurance. Never collapse with FEMA NFHL.', defaultVisible: false, maplibre: { arcgisLayerIds: [104, 438] } },
  { id: 'in-parcels-current', title: 'Indiana Current Parcel Boundaries', authority_class: 'CONTEXT', type: 'arcgis-mapserver', url: 'https://gisdata.in.gov/server/rest/services/Hosted/Parcel_Boundaries_of_Indiana_Current/FeatureServer', attribution: 'IGIO Data Harvest', notes: 'Current statewide harvest layer released 2024-11-13. Not a survey product; county accuracy varies.', defaultVisible: false },
  { id: 'in-roads-current', title: 'Indiana Current Road Centerlines', authority_class: 'CONTEXT', type: 'arcgis-mapserver', url: 'https://gisdata.in.gov/server/rest/services/Hosted/Road_Centerlines_of_Indiana_Current/FeatureServer', attribution: 'IGIO Data Harvest', defaultVisible: false },
  { id: 'indiana-imagery', title: 'Indiana Current Imagery (ImageServer)', authority_class: 'OBSERVATION', type: 'raster', url: 'https://di-ingov.img.arcgis.com/arcgis/rest/services/DynamicWebMercator/Indiana_Current_Imagery/ImageServer', attribution: 'IGIO', notes: 'Current 2022–2025 imagery service; use service-compatible tile/export access.', defaultVisible: true },
  { id: 'indiana-terrain-rgb', title: 'USGS 3DEP Terrain-RGB', authority_class: 'OBSERVATION', type: 'raster-dem', url: '${VITE_TSM_TERRAIN_RGB_URL_TEMPLATE}', attribution: 'USGS 3DEP / TSM tile pipeline', notes: 'Runtime-configured Terrain-RGB XYZ template produced from real 3DEP/best-available lidar. No fabricated terrain fallback.', defaultVisible: true },
  { id: 'in-addresses-current', title: 'Address Points of Indiana Current', authority_class: 'CONTEXT', type: 'arcgis-mapserver', url: 'https://gisdata.in.gov/server/rest/services/Hosted/Address_Points_of_Indiana_Current/FeatureServer', attribution: 'IGIO Data Harvest', defaultVisible: false },
  { id: 'in-plss', title: 'Indiana PLSS State Boundary', authority_class: 'CONTEXT', type: 'arcgis-mapserver', url: 'https://gisdata.in.gov/server/rest/services/Hosted/PLSS_Indiana_State_Boundary/FeatureServer', attribution: 'IGIO / DNR', defaultVisible: false },
  { id: 'posey-cslf', title: 'Posey Changes Since Last FIRM', authority_class: 'CONTEXT', type: 'arcgis-mapserver', url: 'https://gisdata.in.gov/server/rest/services/Hosted/Posey_CSLF_Feb2025/FeatureServer', attribution: 'Indiana GIS / Posey CSLF', notes: 'Preliminary/pending map-change evidence; not equivalent to effective NFHL.', defaultVisible: false },
  { id: 'usgs-3dep-index', title: 'USGS 3DEP Elevation Index', authority_class: 'OBSERVATION', type: 'arcgis-mapserver', url: 'https://index.nationalmap.gov/arcgis/rest/services/3DEPElevationIndex/MapServer', attribution: 'USGS 3DEP', defaultVisible: false },
];

export const HECRAS_INTEGRATION = {
  role: 'Scientific & Simulation Plane — offline / server adapters',
  mesh_targets_ft: { channel_conveyance: [25, 50], near_berm_structures_lag: [25, 40], active_floodplain: [50, 100], overbank_ag: [100, 200] },
  inputs: ['3DEP / best-available terrain with explicit CRS and vertical-datum provenance', 'Hydro-enforced terrain and channel/bank/berm breaklines', 'Land use / Manning n from external evidence layers'],
  workflow: ['Acquire DEM/LiDAR metadata from TNMAccess', 'Clip to AOI; reproject only with recorded transformation', 'RAS Mapper → Create New RAS Terrain', 'Define 2D Flow Areas and breaklines', 'Use USGS/NWPS boundary conditions', 'Export inundation rasters → EvidenceArtifact MODEL_OUTPUT with model_version and SIMULATION_DEMO status'],
  project_constants_ft: { lag: 377.2, bfe: 375.0, berm_crest: 379.8, ffe: 382.5, no_rise_tolerance: 0.0 },
  openmi: 'Future OpenMI 2.0 contracts couple HEC-RAS outputs to TSM Evidence Bus — human gate before regulatory use',
  references: ['https://www.hec.usace.army.mil/software/hec-ras/']
};
