import { useMemo, useState } from 'react';
import { useLoaderData } from 'react-router';
import type { MapTwinLoaderData } from '../types/loaders';
import { SITE } from '../types/site';
import { JURISDICTION_RULES, assessClearanceSupport, type JurisdictionId } from '../lib/jurisdiction-rules';
import { WEB_ENDPOINTS, ENDPOINT_STATUS } from '../lib/web-endpoints';
import { illustrativeHazusLoss } from '../lib/hazus-illustrative';
import { AuthorityBadge, SimulationDemoBanner } from '../components/AuthorityBadge';

export default function MapLibreEocView() {
  const data = useLoaderData() as MapTwinLoaderData;
  const [jurisdiction, setJurisdiction] = useState<JurisdictionId>('INDIANA');
  const [waterStageFt, setWaterStageFt] = useState(data.stage.wse_navd88_ft ?? 0);
  const [showSources, setShowSources] = useState(false);
  const liveStage = data.stage.value_ft;
  const usingLive = liveStage != null && data.stage.source !== 'UNAVAILABLE';
  const liveWseNavd88 = data.stage.wse_navd88_ft;
  const displayWseNavd88 = usingLive ? liveWseNavd88 : waterStageFt;
  const bfeFt = SITE.elevations.bfe_ft;
  const lagFt = SITE.elevations.lag_ft;
  const hasProjectElevations = bfeFt != null && lagFt != null;
  const clearanceFt = hasProjectElevations && displayWseNavd88 != null ? Number((lagFt - displayWseNavd88).toFixed(2)) : null;
  const assessment = useMemo(() => { if (bfeFt == null || lagFt == null || displayWseNavd88 == null) return null; return assessClearanceSupport({ jurisdiction, waterStageFt: displayWseNavd88, bfeFt, lagFt }); }, [jurisdiction, displayWseNavd88, bfeFt, lagFt]);
  const hazus = useMemo(() => lagFt == null || displayWseNavd88 == null ? null : illustrativeHazusLoss(displayWseNavd88, lagFt), [displayWseNavd88, lagFt]);
  const rule = JURISDICTION_RULES[jurisdiction];
  const formatRuleValue = (value: number | undefined, digits: number, unit = '') => value == null ? 'not specified' : `${value.toFixed(digits)}${unit}`;
  const floodBand = useMemo(() => { const stage = liveStage; if (stage == null) return { code: 'UNKNOWN', color: '#94a3b8' }; const s = SITE.noaaGauge.stages; if (s.major != null && stage >= s.major) return { code: 'MAJOR', color: '#f87171' }; if (s.moderate != null && stage >= s.moderate) return { code: 'MODERATE', color: '#fb923c' }; if (s.minor != null && stage >= s.minor) return { code: 'MINOR', color: '#fbbf24' }; if (s.action != null && stage >= s.action) return { code: 'ACTION', color: '#fde047' }; return { code: 'NORMAL', color: '#34d399' }; }, [liveStage]);
  return <div style={{ padding: '1rem 1.25rem', maxWidth: 1100, margin: '0 auto', color: '#e2e8f0' }}>
    <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: 12, marginBottom: 12 }}><div><h1 style={{ margin: 0, fontSize: '1.25rem', color: '#f8fafc' }}>EOC Surface — Community Engineering View</h1><p style={{ margin: '4px 0 0', fontSize: '0.75rem', color: '#64748b' }}>Community-scoped engineering surface · EPSG:{SITE.crs.horizontalEpsg} / {SITE.crs.verticalDatum}</p></div><div style={{ display: 'flex', gap: 8, alignItems: 'center' }}><AuthorityBadge authority_class={usingLive ? 'OBSERVATION' : 'SIMULATION_DEMO'} is_simulation_demo={!usingLive} /><span style={{ fontSize: '0.7rem', fontWeight: 700, color: floodBand.color }}>FLOOD BAND: {floodBand.code}</span></div></div>
    {!usingLive && <SimulationDemoBanner />}{!hasProjectElevations && <div style={{ ...card, marginBottom: 16, color: '#fbbf24' }}>Project-specific BFE/LAG/FFE/berm elevations are not loaded. Engineering comparisons remain unavailable until authoritative project evidence is supplied.</div>}
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
      <section style={card}><h2 style={h2}>Hydrologic plane (decision support)</h2><p style={{ fontSize: '0.7rem', color: '#64748b' }}>Live source: {data.stage.source} {data.stage.gaugeId} · stage {liveStage != null ? `${liveStage.toFixed(2)} ft gage datum` : 'unavailable'}{data.stage.timestamp ? ` · observed ${new Date(data.stage.timestamp).toLocaleString()}` : ''}</p><div style={{ display: 'grid', gap: 6, fontSize: '0.78rem' }}><div>Station WSE: <strong style={{ color: data.stage.wse_navd88_ft == null ? '#fbbf24' : '#38bdf8' }}>{data.stage.wse_navd88_ft == null ? 'unavailable' : `${data.stage.wse_navd88_ft.toFixed(2)} ft NAVD88`}</strong></div><div>Published gage datum: <strong>{data.stage.gage_zero_navd88_ft == null ? 'unverified' : `${data.stage.gage_zero_navd88_ft.toFixed(2)} ft NAVD88`}</strong></div><div style={{ color: '#fbbf24', fontSize: '0.68rem' }}>Station conversion does not transfer WSE to the project site; validated hydraulic profile/model evidence is still required.</div></div><label style={{ display: 'block', marginTop: 10, fontSize: '0.75rem', color: '#94a3b8' }}>Simulation WSE: {waterStageFt.toFixed(2)} ft NAVD88<input aria-label="Simulation water surface elevation" type="range" min={350} max={390} step={0.05} value={waterStageFt} onChange={(e) => setWaterStageFt(parseFloat(e.target.value))} style={{ width: '100%', marginTop: 8 }} disabled={usingLive || !hasProjectElevations} /></label><div style={{ marginTop: 12, fontSize: '0.85rem' }}>Display WSE: <strong style={{ color: '#38bdf8' }}>{displayWseNavd88 == null ? 'unavailable' : `${displayWseNavd88.toFixed(2)} ft NAVD88`}</strong> · LAG clearance: <strong style={{ color: clearanceFt == null ? '#94a3b8' : clearanceFt >= 0 ? '#34d399' : '#f87171' }}>{clearanceFt == null ? 'unavailable' : `${clearanceFt >= 0 ? '+' : ''}${clearanceFt.toFixed(2)} ft`}</strong></div><div style={{ marginTop: 8, fontSize: '0.7rem', color: '#64748b' }}>BFE {bfeFt ?? 'source required'} · LAG {lagFt ?? 'source required'} · FFE {SITE.elevations.ffe_ft ?? 'source required'} · Berm {SITE.elevations.bermCrest_ft ?? 'source required'}</div><div style={{ marginTop: 8, fontSize: '0.68rem', color: '#94a3b8' }}>NWS stage band: {floodBand.code} · action {SITE.noaaGauge.stages.action ?? '—'} ft · minor {SITE.noaaGauge.stages.minor ?? '—'} ft · moderate {SITE.noaaGauge.stages.moderate ?? '—'} ft · major {SITE.noaaGauge.stages.major ?? '—'} ft</div></section>
      <section style={card}><h2 style={h2}>Multi-state regulatory citations</h2><div style={{ display: 'flex', gap: 6, marginBottom: 10 }}>{(['INDIANA', 'ILLINOIS', 'KENTUCKY'] as JurisdictionId[]).map((s) => <button key={s} type="button" onClick={() => setJurisdiction(s)} style={{ flex: 1, padding: '0.35rem', fontSize: '0.65rem', fontWeight: 700, borderRadius: 6, border: jurisdiction === s ? '1px solid #22d3ee' : '1px solid #334155', background: jurisdiction === s ? 'rgba(34,211,238,0.12)' : '#0f172a', color: jurisdiction === s ? '#22d3ee' : '#94a3b8', cursor: 'pointer' }}>{s.slice(0, 3)}</button>)}</div><div style={{ fontSize: '0.85rem', color: '#38bdf8', fontWeight: 600 }}>{rule.name}</div><div style={{ fontSize: '0.65rem', fontFamily: 'monospace', color: '#64748b' }}>{rule.code}</div><p style={{ fontSize: '0.75rem', color: '#cbd5e1' }}>{rule.description}</p><div style={{ fontSize: '0.7rem', color: '#94a3b8' }}>No-rise {formatRuleValue(rule.no_rise_threshold_ft, 2, ' ft')} · Comp {formatRuleValue(rule.compensatory_ratio, 2, 'x')} · Freeboard {formatRuleValue(rule.freeboard_req_ft, 2, ' ft')}</div><div style={{ marginTop: 10, padding: '0.65rem', borderRadius: 8, border: '1px solid #334155', fontSize: '0.75rem' }}>{assessment ? <><div style={{ fontWeight: 700 }}>{assessment.code}</div><div>{assessment.finding}</div><div style={{ marginTop: 4, color: '#64748b', fontSize: '0.65rem' }}>{assessment.note}</div></> : <div style={{ color: '#fbbf24' }}>Regulatory comparison unavailable until project elevations are verified.</div>}</div></section>
      <section style={card}><h2 style={h2}>Illustrative loss curves <AuthorityBadge authority_class="SIMULATION_DEMO" is_simulation_demo size="sm" /></h2>{hazus ? <><p style={{ fontSize: '0.65rem', color: '#f87171' }}>{hazus.disclaimer}</p><div style={{ fontSize: '0.8rem', display: 'grid', gap: 4 }}><div>Depth at structure: {hazus.depthFt.toFixed(2)} ft</div><div>Structural (illustrative): ${hazus.buildingLossUsd.toFixed(0)}</div><div>Contents (illustrative): ${hazus.contentLossUsd.toFixed(0)}</div><div style={{ fontWeight: 700 }}>Total (illustrative): ${hazus.totalLossUsd.toFixed(0)}</div></div><p style={{ fontSize: '0.65rem', color: '#64748b', marginTop: 8 }}>Model: {hazus.model_name} · {hazus.model_version}</p></> : <p style={{ color: '#fbbf24' }}>Illustrative loss output unavailable until project elevation evidence is verified.</p>}</section>
      <section style={card}><h2 style={h2}>Authority endpoints <button type="button" onClick={() => setShowSources(!showSources)} style={{ fontSize: '0.65rem', marginLeft: 8, cursor: 'pointer' }}>{showSources ? 'hide' : 'show'}</button></h2>{showSources && <ul style={{ margin: 0, paddingLeft: 16, fontSize: '0.7rem', fontFamily: 'monospace' }}>{(Object.keys(WEB_ENDPOINTS) as (keyof typeof WEB_ENDPOINTS)[]).map((k) => <li key={k} style={{ marginBottom: 4 }}><span style={{ color: ENDPOINT_STATUS[k] === 'VERIFIED' ? '#34d399' : '#fbbf24' }}>[{ENDPOINT_STATUS[k]}]</span> {k}: {WEB_ENDPOINTS[k].slice(0, 60)}…</li>)}</ul>}<p style={{ fontSize: '0.65rem', color: '#64748b' }}>Provider endpoints are references; live operational data is obtained through the server-side data fabric.</p></section>
    </div><p style={{ marginTop: 16, fontSize: '0.65rem', color: '#475569', textAlign: 'center' }}>Visualization only · Not a regulatory model · Human authority required for LOMA / No-Rise · Simulation controls never substitute for authoritative observations.</p>
  </div>;
}
const card: React.CSSProperties = { background: '#1e293b', borderRadius: 12, padding: '1rem', border: '1px solid #334155' };
const h2: React.CSSProperties = { margin: '0 0 0.5rem', fontSize: '0.8rem', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.06em' };
