#include "TSMNativeWorldFabric.h"
#include "Engine/World.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
bool UTSMWorldInteractionSubsystem::SelectActor(AActor* A){if(!IsValid(A)){ClearSelection();return false;}SelectedActor=A;return true;}void UTSMWorldInteractionSubsystem::ClearSelection(){SelectedActor.Reset();}
FTSMTerrainProbeResult UTSMTerrainProbeComponent::ProbeWorldLocation(const FVector L)const{FTSMTerrainProbeResult R;R.WorldLocation=L;const UWorld*W=GetWorld();if(!W)return R;FHitResult H;const FVector A(L.X,L.Y,L.Z+100000),B(L.X,L.Y,L.Z-100000);FCollisionQueryParams Q(SCENE_QUERY_STAT(TSMTerrainProbe),true);if(!W->LineTraceSingleByChannel(H,A,B,ECC_Visibility,Q))return R;R.bValid=true;R.WorldLocation=H.ImpactPoint;R.ElevationMeters=H.ImpactPoint.Z;const FVector N=H.ImpactNormal.GetSafeNormal();R.SlopeDegrees=FMath::RadiansToDegrees(FMath::Acos(FMath::Clamp(FVector::DotProduct(N,FVector::UpVector),-1.0,1.0)));R.AspectDegrees=FMath::Fmod(FMath::RadiansToDegrees(FMath::Atan2(N.Y,N.X))+360.0,360.0);return R;}
FTSMDistanceMeasurement UTSMMeasurementSubsystem::MeasureDistance(const FVector A,const FVector B){FTSMDistanceMeasurement R;const FVector D=B-A;R.DistanceMeters=D.Size();R.HorizontalDistanceMeters=FVector(D.X,D.Y,0).Size();R.ElevationDifferenceMeters=D.Z;R.GradePercent=R.HorizontalDistanceMeters>KINDA_SMALL_NUMBER?D.Z/R.HorizontalDistanceMeters*100.0:0;return R;}
bool UTSMScenarioTimelineSubsystem::RegisterScenario(const FTSMScenarioDefinition&D){if(D.ScenarioId.IsNone()||D.SourceId.IsEmpty()||D.SourceVersion.IsEmpty()||D.EvidenceClass.IsEmpty())return false;for(const auto&S:Scenarios)if(S.ScenarioId==D.ScenarioId)return false;Scenarios.Add(D);if(ActiveScenario.IsNone())ActiveScenario=D.ScenarioId;return true;}bool UTSMScenarioTimelineSubsystem::SetActiveScenario(FName I){FTSMScenarioDefinition D;if(!GetScenario(I,D))return false;ActiveScenario=I;return true;}bool UTSMScenarioTimelineSubsystem::GetScenario(FName I,FTSMScenarioDefinition&O)const{for(const auto&S:Scenarios)if(S.ScenarioId==I){O=S;return true;}return false;}
FTSMFloodDepthResult UTSMFloodScenarioSubsystem::EvaluateDepth(double G,double W,bool E,const FString&C,const FString&S){FTSMFloodDepthResult R;R.GroundElevationMeters=G;R.WaterSurfaceElevationMeters=W;R.EvidenceClass=C;R.SourceId=S;R.bValidEvidence=E;R.DepthMeters=E?FMath::Max(0.0,W-G):0;R.UncertaintyNote=E?TEXT("Source-bound scenario elevation."):TEXT("No evidence supplied; depth withheld.");return R;}void ATSMFloodSurfaceActor::SetFloodDepth(double D,const FString&C,const FString&S){FloodDepthMeters=FMath::Max(0.0,D);EvidenceClass=C;SourceId=S;}
void ATSMAlignmentActor::SetAlignmentPoints(const TArray<FVector>&P){AlignmentPoints=P;}double ATSMAlignmentActor::GetAlignmentLengthMeters()const{double L=0;for(int32 I=1;I<AlignmentPoints.Num();++I)L+=FVector::Distance(AlignmentPoints[I-1],AlignmentPoints[I]);return L;}
bool ATSMBermDesignActor::SetDesignParameters(const FTSMBermDesignParameters&P){if(P.LengthMeters<0||P.TopWidthMeters<0||P.HeightMeters<0||P.SideSlopeHorizontalToVertical<0)return false;Design=P;return true;}double ATSMBermDesignActor::GetFillVolumeCubicMeters()const{return Design.LengthMeters*Design.HeightMeters*(Design.TopWidthMeters+Design.SideSlopeHorizontalToVertical*Design.HeightMeters);}bool ATSMRoadDesignActor::SetRoadParameters(double W,double G){if(W<0||!FMath::IsFinite(G))return false;WidthMeters=W;TargetGradePercent=G;return true;}void ATSMRoadDesignActor::SetAlignmentPoints(const TArray<FVector>&P){AlignmentPoints=P;}FTSMCutFillResult UTSMCutFillSubsystem::EstimateCutFill(double E,double D,double W,double L){FTSMCutFillResult R;const double V=FMath::Max(0.0,W)*FMath::Max(0.0,L)*FMath::Abs(D-E);if(D>=E)R.FillVolumeCubicMeters=V;else R.CutVolumeCubicMeters=V;return R;}double UTSMQuantitySubsystem::EstimateBermVolume(double L,double W,double H,double Z){if(L<0||W<0||H<0||Z<0)return 0;return L*H*(W+Z*H);}
void UTSMScenarioSnapshot::Initialize(FString A,FString B,FString C,FString D){ScenarioId=MoveTemp(A);SourceManifestHash=MoveTemp(B);ResultManifestHash=MoveTemp(C);Uncertainty=MoveTemp(D);}bool UTSMProvenanceSubsystem::RegisterEvidence(const FTSMProvenanceRecord&R){if(R.EvidenceId.IsEmpty()||R.SourceId.IsEmpty()||R.Version.IsEmpty())return false;for(const auto&X:Records)if(X.EvidenceId==R.EvidenceId)return false;Records.Add(R);return true;}bool UTSMProvenanceSubsystem::GetEvidence(FString I,FTSMProvenanceRecord&O)const{for(const auto&R:Records)if(R.EvidenceId==I){O=R;return true;}return false;}
bool UTSMBlueprintGenerationSubsystem::GenerateBlueprintReadyPackage(const FTSMDesignIR&D,FString&O)const{if(D.DesignId.IsEmpty()||D.DesignStatus!=TEXT("conceptual")||D.EvidenceReference.IsEmpty()||D.ProvenanceHash.IsEmpty())return false;O=FPaths::Combine(FPaths::ProjectSavedDir(),TEXT("TSM"),TEXT("DesignPackages"),D.DesignId);IFileManager::Get().MakeDirectory(*O,true);return FFileHelper::SaveStringToFile(FString::Printf(TEXT("# Blueprint-Ready Design IR\nDesign=%s\nScenario=%s\nEvidence=%s\nProvenance=%s\n"),*D.DesignId,*D.ScenarioId,*D.EvidenceReference,*D.ProvenanceHash),*FPaths::Combine(O,TEXT("blueprint-ready-design-ir.md")),FFileHelper::EEncodingOptions::ForceUTF8);}
bool UTSMUsdExportAdapter::ExportDesignManifest(const FTSMDesignIR&D,const FString&P){return !P.IsEmpty()&&!D.DesignId.IsEmpty()&&FFileHelper::SaveStringToFile(FString::Printf(TEXT("TSM USD exchange manifest\nDesignId=%s\nScenarioId=%s\nCRS=%s\n"),*D.DesignId,*D.ScenarioId,*D.CRS),*P,FFileHelper::EEncodingOptions::ForceUTF8);}bool UTSMBIMExportAdapter::ExportDesignManifest(const FTSMDesignIR&D,const FString&P){return !P.IsEmpty()&&!D.DesignId.IsEmpty()&&FFileHelper::SaveStringToFile(FString::Printf(TEXT("TSM BIM exchange manifest\nDesignId=%s\nScenarioId=%s\nVerticalDatum=%s\n"),*D.DesignId,*D.ScenarioId,*D.VerticalDatum),*P,FFileHelper::EEncodingOptions::ForceUTF8);}
bool UTSMCinematicCameraSubsystem::ApplyPreset(const FTSMCameraPreset&P)const{return P.FocalLengthMm>0&&P.Aperture>0&&P.FocusDistanceMeters>=0;}FTSMCameraPreset UTSMCameraPresetLibrary::EngineeringInspectionPreset(){FTSMCameraPreset P;P.Name=TEXT("EngineeringInspection");P.Aperture=8;P.bEngineeringInspection=true;return P;}FTSMCameraPreset UTSMCameraPresetLibrary::CinematicEstablishingPreset(){FTSMCameraPreset P;P.Name=TEXT("CinematicEstablishing");P.FocalLengthMm=24;P.Aperture=2.8f;return P;}FTSMLightingPreset UTSMLightingPresetLibrary::EngineeringNeutral(){FTSMLightingPreset P;P.Name=TEXT("EngineeringNeutral");return P;}FTSMLightingPreset UTSMLightingPresetLibrary::StormInspection(){FTSMLightingPreset P;P.Name=TEXT("StormInspection");P.SunIntensity=4;return P;}FTSMWeatherPreset UTSMWeatherPresetLibrary::ClearEngineering(){FTSMWeatherPreset P;P.Name=TEXT("ClearEngineering");return P;}FTSMWeatherPreset UTSMWeatherPresetLibrary::StormScenario(){FTSMWeatherPreset P;P.Name=TEXT("StormScenario");P.CloudCoverage=.85f;P.FogDensity=.08f;return P;}