#pragma once
#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "Subsystems/WorldSubsystem.h"
#include "Components/ActorComponent.h"
#include "Components/SceneComponent.h"
#include "GameFramework/Actor.h"
#include "UObject/Object.h"
#include "TSMNativeWorldFabric.generated.h"

UENUM(BlueprintType) enum class ETSMScenarioCategory:uint8{Historical,Observed,Regulatory,Current,Design,Future,Custom};
USTRUCT(BlueprintType) struct FTSMSelectionMetadata{GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) FString ObjectId; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString ObjectType; UPROPERTY(EditAnywhere,BlueprintReadWrite) FVector GeographicPosition=FVector::ZeroVector; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString CRS; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString VerticalDatum; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString SourceId; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString SourceVersion; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString SourceHash;};
USTRUCT(BlueprintType) struct FTSMTerrainProbeResult{GENERATED_BODY() UPROPERTY(BlueprintReadOnly) bool bValid=false; UPROPERTY(BlueprintReadOnly) double ElevationMeters=0; UPROPERTY(BlueprintReadOnly) double SlopeDegrees=0; UPROPERTY(BlueprintReadOnly) double AspectDegrees=0; UPROPERTY(BlueprintReadOnly) FVector WorldLocation=FVector::ZeroVector; UPROPERTY(BlueprintReadOnly) FString Method=TEXT("Landscape/World line trace"); UPROPERTY(BlueprintReadOnly) FString UncertaintyNote=TEXT("Native geometry probe; evidence fabric supplies CRS/datum.");};
USTRUCT(BlueprintType) struct FTSMDistanceMeasurement{GENERATED_BODY() UPROPERTY(BlueprintReadOnly) double DistanceMeters=0; UPROPERTY(BlueprintReadOnly) double HorizontalDistanceMeters=0; UPROPERTY(BlueprintReadOnly) double ElevationDifferenceMeters=0; UPROPERTY(BlueprintReadOnly) double GradePercent=0;};
USTRUCT(BlueprintType) struct FTSMScenarioDefinition{GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadOnly) FName ScenarioId; UPROPERTY(EditAnywhere,BlueprintReadOnly) ETSMScenarioCategory Category=ETSMScenarioCategory::Current; UPROPERTY(EditAnywhere,BlueprintReadOnly) FString SourceId; UPROPERTY(EditAnywhere,BlueprintReadOnly) FString SourceVersion; UPROPERTY(EditAnywhere,BlueprintReadOnly) FString SourceHash; UPROPERTY(EditAnywhere,BlueprintReadOnly) FString EvidenceClass;};
USTRUCT(BlueprintType) struct FTSMFloodDepthResult{GENERATED_BODY() UPROPERTY(BlueprintReadOnly) bool bValidEvidence=false; UPROPERTY(BlueprintReadOnly) double GroundElevationMeters=0; UPROPERTY(BlueprintReadOnly) double WaterSurfaceElevationMeters=0; UPROPERTY(BlueprintReadOnly) double DepthMeters=0; UPROPERTY(BlueprintReadOnly) FString EvidenceClass; UPROPERTY(BlueprintReadOnly) FString SourceId; UPROPERTY(BlueprintReadOnly) FString UncertaintyNote;};
USTRUCT(BlueprintType) struct FTSMBermDesignParameters{GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) double LengthMeters=0; UPROPERTY(EditAnywhere,BlueprintReadWrite) double TopWidthMeters=0; UPROPERTY(EditAnywhere,BlueprintReadWrite) double HeightMeters=0; UPROPERTY(EditAnywhere,BlueprintReadWrite) double SideSlopeHorizontalToVertical=0;};
USTRUCT(BlueprintType) struct FTSMCutFillResult{GENERATED_BODY() UPROPERTY(BlueprintReadOnly) double FillVolumeCubicMeters=0; UPROPERTY(BlueprintReadOnly) double CutVolumeCubicMeters=0;};
USTRUCT(BlueprintType) struct FTSMDesignIR{GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) FString DesignId; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString ScenarioId; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString CRS; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString VerticalDatum; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString EvidenceReference; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString ProvenanceHash; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString DesignStatus=TEXT("conceptual"); UPROPERTY(EditAnywhere,BlueprintReadWrite) TMap<FString,double> Parameters;};
USTRUCT(BlueprintType) struct FTSMProvenanceRecord{GENERATED_BODY() UPROPERTY(BlueprintReadOnly) FString EvidenceId; UPROPERTY(BlueprintReadOnly) FString SourceId; UPROPERTY(BlueprintReadOnly) FString Dataset; UPROPERTY(BlueprintReadOnly) FString Version; UPROPERTY(BlueprintReadOnly) FString Transformation; UPROPERTY(BlueprintReadOnly) FString Model; UPROPERTY(BlueprintReadOnly) FString Calculation; UPROPERTY(BlueprintReadOnly) FString Result; UPROPERTY(BlueprintReadOnly) FString Visualization; UPROPERTY(BlueprintReadOnly) FString Artifact;};
USTRUCT(BlueprintType) struct FTSMMaterialProperties{GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) FString MaterialId; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString Name; UPROPERTY(EditAnywhere,BlueprintReadWrite) double DensityKgPerM3=0; UPROPERTY(EditAnywhere,BlueprintReadWrite) double Roughness=0; UPROPERTY(EditAnywhere,BlueprintReadWrite) double Permeability=0; UPROPERTY(EditAnywhere,BlueprintReadWrite) double Porosity=0; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString SourceId; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString Uncertainty;};
USTRUCT(BlueprintType) struct FTSMCameraPreset{GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) FName Name; UPROPERTY(EditAnywhere,BlueprintReadWrite) float FocalLengthMm=35; UPROPERTY(EditAnywhere,BlueprintReadWrite) float Aperture=5.6f; UPROPERTY(EditAnywhere,BlueprintReadWrite) float FocusDistanceMeters=100; UPROPERTY(EditAnywhere,BlueprintReadWrite) bool bEngineeringInspection=false;};
USTRUCT(BlueprintType) struct FTSMLightingPreset{GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) FName Name; UPROPERTY(EditAnywhere,BlueprintReadWrite) float SunIntensity=10; UPROPERTY(EditAnywhere,BlueprintReadWrite) float ExposureBias=0;};
USTRUCT(BlueprintType) struct FTSMWeatherPreset{GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) FName Name; UPROPERTY(EditAnywhere,BlueprintReadWrite) float CloudCoverage=0; UPROPERTY(EditAnywhere,BlueprintReadWrite) float FogDensity=0;};
USTRUCT(BlueprintType) struct FTSMRenderProvenance{GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) FString ScenarioId; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString SourceManifestHash; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString CameraPreset; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString LightingPreset; UPROPERTY(EditAnywhere,BlueprintReadWrite) FString Renderer;};

UCLASS() class TSMNATIVE_API UTSMMaterialLibrary:public UObject{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Materials")static bool Validate(const FTSMMaterialProperties& P){return !P.MaterialId.IsEmpty()&&!P.Name.IsEmpty()&&!P.SourceId.IsEmpty()&&P.DensityKgPerM3>=0&&P.Roughness>=0&&P.Permeability>=0&&P.Porosity>=0&&P.Porosity<=1;}};
USTRUCT(BlueprintType) struct FTSMSourceMetadata{GENERATED_BODY() UPROPERTY(BlueprintReadOnly) FString SourceId; UPROPERTY(BlueprintReadOnly) FString Authority; UPROPERTY(BlueprintReadOnly) FString DatasetType; UPROPERTY(BlueprintReadOnly) FString Version; UPROPERTY(BlueprintReadOnly) FString Hash;};
UCLASS() class TSMNATIVE_API UTSMSourceInspector:public UObject{GENERATED_BODY() public:UFUNCTION(BlueprintPure,Category="TSM|Evidence")static bool IsComplete(const FTSMSourceMetadata& M){return !M.SourceId.IsEmpty()&&!M.Authority.IsEmpty()&&!M.DatasetType.IsEmpty()&&!M.Version.IsEmpty()&&!M.Hash.IsEmpty();}};
UCLASS() class TSMNATIVE_API UTSMWorldInteractionSubsystem:public UGameInstanceSubsystem{GENERATED_BODY() public: UFUNCTION(BlueprintCallable,Category="TSM|World") bool SelectActor(AActor* Actor); UFUNCTION(BlueprintCallable,Category="TSM|World") void ClearSelection(); UFUNCTION(BlueprintPure,Category="TSM|World") AActor* GetSelectedActor()const{return SelectedActor.Get();} private:TWeakObjectPtr<AActor> SelectedActor;};
UCLASS(ClassGroup=(TSM),meta=(BlueprintSpawnableComponent)) class TSMNATIVE_API UTSMGeoSelectionComponent:public UActorComponent{GENERATED_BODY() public: UFUNCTION(BlueprintPure,Category="TSM|World") FTSMSelectionMetadata GetSelectionMetadata()const{return Metadata;} UFUNCTION(BlueprintCallable,Category="TSM|World") void SetSelectionMetadata(const FTSMSelectionMetadata& M){Metadata=M;} private:UPROPERTY() FTSMSelectionMetadata Metadata;};
UCLASS(ClassGroup=(TSM),meta=(BlueprintSpawnableComponent)) class TSMNATIVE_API UTSMTerrainProbeComponent:public UActorComponent{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Terrain") FTSMTerrainProbeResult ProbeWorldLocation(FVector WorldLocation)const;};
UCLASS() class TSMNATIVE_API UTSMMeasurementSubsystem:public UGameInstanceSubsystem{GENERATED_BODY() public:UFUNCTION(BlueprintPure,Category="TSM|Measure") static FTSMDistanceMeasurement MeasureDistance(FVector A,FVector B);};
UCLASS(ClassGroup=(TSM),meta=(BlueprintSpawnableComponent)) class TSMNATIVE_API UTSMProfileComponent:public UActorComponent{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Design")void SetProfileElevations(const TArray<double>& InElevations){ProfileElevations=InElevations;} UFUNCTION(BlueprintPure,Category="TSM|Design")double GetAverageElevation()const{if(ProfileElevations.IsEmpty())return 0;double S=0;for(double V:ProfileElevations)S+=V;return S/ProfileElevations.Num();} private:UPROPERTY()TArray<double> ProfileElevations;};
UCLASS() class TSMNATIVE_API UTSMScenarioTimelineSubsystem:public UGameInstanceSubsystem{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Scenario") bool RegisterScenario(const FTSMScenarioDefinition& D); UFUNCTION(BlueprintCallable,Category="TSM|Scenario") bool SetActiveScenario(FName Id); UFUNCTION(BlueprintPure,Category="TSM|Scenario") FName GetActiveScenario()const{return ActiveScenario;} UFUNCTION(BlueprintPure,Category="TSM|Scenario") bool GetScenario(FName Id,FTSMScenarioDefinition& Out)const; private:UPROPERTY() TArray<FTSMScenarioDefinition> Scenarios;UPROPERTY()FName ActiveScenario;};
UCLASS() class TSMNATIVE_API UTSMFloodScenarioSubsystem:public UGameInstanceSubsystem{GENERATED_BODY() public:UFUNCTION(BlueprintPure,Category="TSM|Flood") static FTSMFloodDepthResult EvaluateDepth(double Ground,double WSE,bool bEvidence,const FString& EvidenceClass,const FString& SourceId); UFUNCTION(BlueprintCallable,Category="TSM|Flood") bool LoadScenario(FName ScenarioId);};
UCLASS() class TSMNATIVE_API ATSMFloodSurfaceActor:public AActor{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Flood") void SetFloodDepth(double D,const FString& C,const FString& S);UPROPERTY(BlueprintReadOnly)double FloodDepthMeters=0;UPROPERTY(BlueprintReadOnly)FString EvidenceClass;UPROPERTY(BlueprintReadOnly)FString SourceId;};
UCLASS(ClassGroup=(TSM),meta=(BlueprintSpawnableComponent)) class TSMNATIVE_API UTSMFloodContourComponent:public USceneComponent{GENERATED_BODY() public:UPROPERTY(EditAnywhere,BlueprintReadWrite)double ContourIntervalMeters=.25;UPROPERTY(EditAnywhere,BlueprintReadWrite)bool bIsModeledScenario=false;UPROPERTY(EditAnywhere,BlueprintReadWrite)bool bIsCinematicPresentation=false;};
UCLASS() class TSMNATIVE_API ATSMAlignmentActor:public AActor{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Design")void SetAlignmentPoints(const TArray<FVector>& P);UFUNCTION(BlueprintPure,Category="TSM|Design")double GetAlignmentLengthMeters()const;UPROPERTY(EditAnywhere,BlueprintReadOnly)TArray<FVector> AlignmentPoints;};
UCLASS() class TSMNATIVE_API ATSMBermDesignActor:public AActor{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Design")bool SetDesignParameters(const FTSMBermDesignParameters& P);UFUNCTION(BlueprintPure,Category="TSM|Design")double GetFillVolumeCubicMeters()const;UPROPERTY(EditAnywhere,BlueprintReadOnly)FTSMBermDesignParameters Design;};
UCLASS() class TSMNATIVE_API ATSMRoadDesignActor:public AActor{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Design")bool SetRoadParameters(double Width,double GradePercent);UFUNCTION(BlueprintCallable,Category="TSM|Design")void SetAlignmentPoints(const TArray<FVector>& P);UPROPERTY(BlueprintReadOnly)double WidthMeters=0;UPROPERTY(BlueprintReadOnly)double TargetGradePercent=0;UPROPERTY(BlueprintReadOnly)TArray<FVector> AlignmentPoints;};
UCLASS() class TSMNATIVE_API UTSMCutFillSubsystem:public UGameInstanceSubsystem{GENERATED_BODY() public:UFUNCTION(BlueprintPure,Category="TSM|Design")static FTSMCutFillResult EstimateCutFill(double Existing,double Design,double Width,double Length);};
UCLASS() class TSMNATIVE_API UTSMQuantitySubsystem:public UGameInstanceSubsystem{GENERATED_BODY() public:UFUNCTION(BlueprintPure,Category="TSM|Design")static double EstimateBermVolume(double L,double W,double H,double Z);};
UCLASS() class TSMNATIVE_API UTSMDesignIntermediateRepresentation:public UObject{GENERATED_BODY() public:UFUNCTION(BlueprintPure,Category="TSM|Design")static FString GetContractVersion(){return TEXT("TSM-Design-IR-1.0");}};
UCLASS(BlueprintType) class TSMNATIVE_API UTSMEvidenceObject:public UObject{GENERATED_BODY() public:UPROPERTY(EditAnywhere,BlueprintReadWrite)FString EvidenceId;UPROPERTY(EditAnywhere,BlueprintReadWrite)FString EvidenceClass;UPROPERTY(EditAnywhere,BlueprintReadWrite)FString SourceId;UPROPERTY(EditAnywhere,BlueprintReadWrite)FString SourceVersion;UPROPERTY(EditAnywhere,BlueprintReadWrite)FString SourceHash;};
UCLASS() class TSMNATIVE_API UTSMProvenanceSubsystem:public UGameInstanceSubsystem{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Evidence")bool RegisterEvidence(const FTSMProvenanceRecord& R);UFUNCTION(BlueprintPure,Category="TSM|Evidence")bool GetEvidence(FString Id,FTSMProvenanceRecord& Out)const;private:UPROPERTY()TArray<FTSMProvenanceRecord> Records;};
UCLASS() class TSMNATIVE_API UTSMScenarioSnapshot:public UObject{GENERATED_BODY() public:UPROPERTY(BlueprintReadOnly)FString ScenarioId;UPROPERTY(BlueprintReadOnly)FString SourceManifestHash;UPROPERTY(BlueprintReadOnly)FString ResultManifestHash;UPROPERTY(BlueprintReadOnly)FString Uncertainty;UFUNCTION(BlueprintCallable)void Initialize(FString A,FString B,FString C,FString D){ScenarioId=MoveTemp(A);SourceManifestHash=MoveTemp(B);ResultManifestHash=MoveTemp(C);Uncertainty=MoveTemp(D);}};
UCLASS(ClassGroup=(TSM),meta=(BlueprintSpawnableComponent)) class TSMNATIVE_API UTSMEvidenceOverlay:public USceneComponent{GENERATED_BODY() public:UPROPERTY(EditAnywhere,BlueprintReadWrite)bool bShowSource=true;UPROPERTY(EditAnywhere,BlueprintReadWrite)bool bShowUncertainty=true;UPROPERTY(EditAnywhere,BlueprintReadWrite)FString EvidenceClass;};
UCLASS() class TSMNATIVE_API UTSMBlueprintGenerationSubsystem:public UGameInstanceSubsystem{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Artifacts")bool GenerateBlueprintReadyPackage(const FTSMDesignIR& D,FString& OutDirectory)const;};
UCLASS() class TSMNATIVE_API UTSMUsdExportAdapter:public UObject{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Artifacts")static bool ExportDesignManifest(const FTSMDesignIR& D,const FString& P);};
UCLASS() class TSMNATIVE_API UTSMBIMExportAdapter:public UObject{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Artifacts")static bool ExportDesignManifest(const FTSMDesignIR& D,const FString& P);};
UCLASS() class TSMNATIVE_API UTSMCinematicCameraSubsystem:public UWorldSubsystem{GENERATED_BODY() public:UFUNCTION(BlueprintCallable,Category="TSM|Camera")bool ApplyPreset(const FTSMCameraPreset& P)const;};
UCLASS() class TSMNATIVE_API UTSMCameraPresetLibrary:public UObject{GENERATED_BODY() public:UFUNCTION(BlueprintPure,Category="TSM|Camera")static FTSMCameraPreset EngineeringInspectionPreset();UFUNCTION(BlueprintPure,Category="TSM|Camera")static FTSMCameraPreset CinematicEstablishingPreset();};
UCLASS() class TSMNATIVE_API UTSMLightingPresetLibrary:public UObject{GENERATED_BODY() public:UFUNCTION(BlueprintPure,Category="TSM|Lighting")static FTSMLightingPreset EngineeringNeutral();UFUNCTION(BlueprintPure,Category="TSM|Lighting")static FTSMLightingPreset StormInspection();};
UCLASS() class TSMNATIVE_API UTSMWeatherPresetLibrary:public UObject{GENERATED_BODY() public:UFUNCTION(BlueprintPure,Category="TSM|Weather")static FTSMWeatherPreset ClearEngineering();UFUNCTION(BlueprintPure,Category="TSM|Weather")static FTSMWeatherPreset StormScenario();};
UCLASS() class TSMNATIVE_API UTSMSequencerIntegration:public UWorldSubsystem{GENERATED_BODY() public:UFUNCTION(BlueprintPure)static FString GetScenarioTrackContractVersion(){return TEXT("TSM-Sequencer-1.0");}};
UCLASS() class TSMNATIVE_API UTSMMovieRenderSubsystem:public UWorldSubsystem{GENERATED_BODY() public:UFUNCTION(BlueprintPure)static bool ValidateRenderProvenance(const FTSMRenderProvenance& P){return !P.ScenarioId.IsEmpty()&&!P.SourceManifestHash.IsEmpty()&&!P.CameraPreset.IsEmpty()&&!P.LightingPreset.IsEmpty()&&!P.Renderer.IsEmpty();}};
UCLASS() class TSMNATIVE_API UTSMFloodDepthMaterial:public UObject{GENERATED_BODY() public:UFUNCTION(BlueprintPure)static double NormalizeDepth(double D,double Max){return D<0||Max<=0?0:FMath::Clamp(D/Max,0.0,1.0);}};
